version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pms_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pms_user
      POSTGRES_PASSWORD: pms_pass
      POSTGRES_DB: pms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

